using HospitalManagement.Application.DTOs.Auth;
using HospitalManagement.Application.Interfaces;
using HospitalManagement.Domain.Entities;
using HospitalManagement.Domain.Enums;
using Microsoft.Extensions.Configuration;
using Microsoft.IdentityModel.Tokens;
using System;
using System.Collections.Generic;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace HospitalManagement.Application.Services
{
    // This service handles everything related to registering and logging in.
    // It uses IUserRepository (interface) — not the actual database class.
    // This means we can mock it in unit tests easily instead of real ones so tests never touch a real database.
    // IConfiguration gives us access to values in appsettings.json — like the JWT secret key.
    public class AuthService : IAuthService
    {   // These private members are declared at the top : class level variables
        // readonly — once set in the constructor, these can never be reassigned.
        private readonly IUserRepository _userRepository;
        private readonly IDoctorRepository _doctorRepository;
        private readonly IPatientRepository _patientRepository;
        private readonly IConfiguration _configuration;

        // Constructor injection — ASP.NET Core automatically provides these dependencies
        // Why use interfaces? we make our own interfaces so you can swap implementations and mock it in tests.
        // _userRepo = userRepo : Saving the variable for later use since the variable handed to the constructor would disappear after the constructor finishes 
        public AuthService(
            IUserRepository userRepository,
            IDoctorRepository doctorRepository,
            IPatientRepository patientRepository,
            IConfiguration configuration)       // ASP.NET Core provides this automatically
        {
            _userRepository = userRepository;
            _doctorRepository = doctorRepository;
            _patientRepository = patientRepository;
            _configuration = configuration;
        }

        public async Task<AuthResponse> RegisterAsync(RegisterRequest request)  // returns AuthResponse object (the JWT token + user details)
        {
            // 1. Check if email already exists
            // If email not found we throw an exception and ExceptionMiddleware catches the exception and automatically sends back a 400 Bad Request
            if (await _userRepository.EmailExistsAsync(request.Email))
                throw new InvalidOperationException("Email is already registered.");

            // 2. Hash the password — NEVER store plain text
            var passwordHash = BCrypt.Net.BCrypt.HashPassword(request.Password);

            // 3. Create the User record
            // At this point the user object only exists in memory
            var user = new User
            {
                FullName = request.FullName,
                Email = request.Email.ToLower(),
                PasswordHash = passwordHash,
                Role = request.Role
            };

            var createdUser = await _userRepository.CreateAsync(user);      // Save The User To Database with a unique ID generated by SQL Server

            // 4. Create role-specific profile
            if (request.Role == UserRole.Doctor)
            {   // if Specialization or LicenceNumber is missing then throw an exception, if not move ahead and save doctor details
                if (string.IsNullOrWhiteSpace(request.Specialization) || string.IsNullOrWhiteSpace(request.LicenseNumber))
                    throw new InvalidOperationException("Specialization and LicenseNumber are required for doctors.");

                var doctor = new Doctor
                {
                    UserId = createdUser.Id,        // The UserId (Unique id generated by SQL Server) is the thread that ties the Doctor record back to the User record. 
                    Specialization = request.Specialization,
                    LicenseNumber = request.LicenseNumber,
                    PhoneNumber = request.PhoneNumber ?? string.Empty       // ?? means "use this if the left side is null"
                };
                await _doctorRepository.CreateAsync(doctor);
            }
            else if (request.Role == UserRole.Patient)
            {
                if (request.DateOfBirth == null || string.IsNullOrWhiteSpace(request.Gender))
                    throw new InvalidOperationException("DateOfBirth and Gender are required for patients.");

                var patient = new Patient
                {
                    UserId = createdUser.Id,
                    DateOfBirth = request.DateOfBirth.Value,
                    Gender = request.Gender,
                    PhoneNumber = request.PhoneNumber ?? string.Empty,
                    Address = request.Address ?? string.Empty,
                    BloodGroup = request.BloodGroup
                };
                await _patientRepository.CreateAsync(patient);
            }

            // 5. Generate and return JWT token
            return GenerateToken(createdUser);
        }

        public async Task<AuthResponse> LoginAsync(LoginRequest request)
        {
            // 1. Find user by email
            var user = await _userRepository.GetByEmailAsync(request.Email.ToLower());

            // 2. Verify email exists and password matches
            // We use the same error message for both cases — prevents attackers from knowing which one failed
            if (user == null || !BCrypt.Net.BCrypt.Verify(request.Password, user.PasswordHash))
                throw new UnauthorizedAccessException("Invalid email or password.");

            if (!user.IsActive)
                throw new UnauthorizedAccessException("Account is deactivated.");

            // 3. Generate and return JWT token
            return GenerateToken(user);
        }

        // Private method — only used inside this class
        private AuthResponse GenerateToken(User user)       // returns an AuthResponse object containing the token and user details.
        {
            // Claims are pieces of info(facts about the person like an ID card) we embed inside the JWT token
            // Every time this person makes a request, the API reads these claims from the token
            // Think of a JWT token like a sealed envelope with information written on it. Anyone can read what's written on the outside (the claims), but they can't tamper with it without breaking the seal (the signature).
            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),   // when a patient books an appointment, we read this claim to know which patient is making the request without DB call.
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.Name, user.FullName),
                new Claim(ClaimTypes.Role, user.Role.ToString())    // user.Role is UserRole.Doctor (an enum value). .ToString() converts it to the string "Doctor"
            };  // This is what [Authorize(Roles = "Doctor")] on controllers reads. When a request comes in, ASP.NET Core checks this claim — if it says "Doctor", only doctor-protected endpoints are accessible.

            // The secret key from appsettings.json is used to sign the token. The signature ensures nobody can tamper with the claims.
            // If someone changes Role from "Patient" to "Admin" in the token, the signature check fails and the token is rejected.
            // HmacSha256 is the signing algorithm — a standard cryptographic algorithm.
            // _configuration["Jwt:SecretKey"] — reads the secret key from appsettings.json (This key lives only on your server)
            // ! tells the compiler I know this could theoretically be null but I guarantee it won't be, I have this key in appsettings.json.
            // Encoding.UTF8.GetBytes(...) — converts the secret key string into a byte array because the cryptographic functions work with bytes, not readable text
            // new SymmetricSecurityKey(...) — wraps those bytes into a security key object that the JWT library understands.
            // Symmetric means the same key is used to both sign and verify the token.
            // Server signs token with SecretKey    →  "eyJhbGci..."    ,    User sends token back in request     →  "eyJhbGci..."
            // Server verifies token with SecretKey →  ✅ valid / ❌ tampered
            var key = new SymmetricSecurityKey(
                Encoding.UTF8.GetBytes(_configuration["Jwt:SecretKey"]!));
            // Token contents + Secret Key  →  HmacSha256  →  unique signature
            // If anyone changes even one character in the token, the signature no longer matches ; the server rejects it instantly.
            var credentials = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);   // This combines what key to use and which algorithm to sign with.

            var expiresAt = DateTime.UtcNow.AddHours(8);

            var token = new JwtSecurityToken(                   // Building The Actual Token
                issuer: _configuration["Jwt:Issuer"],           // who created this token (our API)
                audience: _configuration["Jwt:Audience"],       // who this token is for (our client)
                claims: claims,
                expires: expiresAt,
                signingCredentials: credentials
            );

            return new AuthResponse                             // Convert Token to String and Return
            {
                Token = new JwtSecurityTokenHandler().WriteToken(token),    // new JwtSecurity...(token) : converts the token object into the actual JWT string like "eyJhbGci..." that gets sent to the caller.
                FullName = user.FullName,
                Email = user.Email,
                Role = user.Role.ToString(),
                ExpiresAt = expiresAt
            };
        }
    }
}
